HOST_DIR := host
SORTING_DIR := dpu
BENCHMARK_DIR := benchmark
BUILDDIR ?= bin

TYPE ?= UINT32
BLOCK_SIZE ?= 2048
SEQREAD_CACHE_SIZE ?= 256
NR_DPUS ?= 1
NR_TASKLETS ?= 1
PERF ?= 1
CHECK_SANITY ?= 1

define conf_filename
	${BUILDDIR}/.NR_DPUS_$(1)_NR_TASKLETS_$(2)_TYPE_$(3)_BLOCK_SIZE_$(4)_SEQREAD_CACHE_SIZE_$(5).conf
endef
CONF := $(call conf_filename,${NR_DPUS},${NR_TASKLETS},${TYPE},${BLOCK_SIZE},${SEQREAD_CACHE_SIZE})

HOST_TARGET := ${BUILDDIR}/host
SORTING_TARGET := ${BUILDDIR}/sorting
BENCHMARK_TARGET := ${BUILDDIR}/benchmark

COMMON_INCLUDES := support
HOST_SOURCES := $(wildcard ${HOST_DIR}/*.c)
SORTING_SOURCES := $(wildcard ${SORTING_DIR}/*.c)
BENCHMARK_SOURCES := $(wildcard ${BENCHMARK_DIR}/*.c) $(filter-out ${SORTING_DIR}/task.c, ${SORTING_SOURCES})

.PHONY: all clean test

__dirs := $(shell mkdir -p ${BUILDDIR})

COMMON_FLAGS := -Wall -Wextra -g -I${COMMON_INCLUDES}
HOST_FLAGS := ${COMMON_FLAGS} -std=c11 -O3 `dpu-pkg-config --cflags --libs dpu` -DNR_TASKLETS=${NR_TASKLETS} -DNR_DPUS=${NR_DPUS} -DBLOCK_SIZE=${BLOCK_SIZE} -D${TYPE} -DSORTING_BINARY=\"./${SORTING_TARGET}\" -DBENCHMARK_BINARY=\"./${BENCHMARK_TARGET}\"
SORTING_FLAGS := ${COMMON_FLAGS} -O2 -DNR_TASKLETS=${NR_TASKLETS} -DBLOCK_SIZE=${BLOCK_SIZE} -D${TYPE} -DSEQREAD_CACHE_SIZE=${SEQREAD_CACHE_SIZE} -DPERF=${PERF} -DCHECK_SANITY=${CHECK_SANITY} -DSTACK_SIZE_DEFAULT=512
BENCHMARK_FLAGS := ${SORTING_FLAGS} -Idpu

all: ${HOST_TARGET} ${SORTING_TARGET}

${CONF}:
	$(RM) $(call conf_filename,*,*)
	touch ${CONF}

${HOST_TARGET}: ${HOST_SOURCES} ${COMMON_INCLUDES} ${CONF}
	$(CC) -o $@ ${HOST_SOURCES} ${HOST_FLAGS}

${SORTING_TARGET}: ${SORTING_SOURCES} ${COMMON_INCLUDES} ${CONF}
	dpu-upmem-dpurte-clang ${SORTING_FLAGS} -o $@ ${SORTING_SOURCES}

clean:
	$(RM) -r $(BUILDDIR)

run: all
	./${HOST_TARGET}

test: run